M48
; DRILL file KiCad 10.0.1 date 2026-08-15T12:37:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-15T12:37:23+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X130.141Y-83.628
X130.141Y-89.408
T2
X96.134Y-70.148
X104.114Y-70.148
M30
